name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]


jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: "Install dependencies"
      run: |
        pnpm install
    
    - name: "Build site"
      env:
        NUXT_APP_BASE_URL: "${{ github.event_name == 'push' && '/' || '/kokoko/' }}"
      run: |
        echo "Appplication base url: ${NUXT_APP_BASE_URL}"
        pnpm generate
    
    - name: "PR: site preview"
      if: ${{ github.event_name == 'pull_request' }}
      uses: afc163/surge-preview@v1
      with:
        surge_token: ${{ secrets.SURGE_TOKEN }}
        build: |
          echo "not running npm"
        dist: .output/public
        teardown: 'true'

    - name: Upload static files as artifact
      if: ${{ github.event_name == 'push' }}
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: .output/public


  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
